version: '3'
services:
  database:
    image: postgres:13.0-alpine
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=uic
      - POSTGRES_PASSWORD=abcd1234
      - POSTGRES_DB=mydb
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      mynet:
        aliases:
          - database
    hostname: database
    command: postgres -c 'max_connections=200'

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 5001:5000
    volumes:
      - ./backend:/app 
    depends_on:
      - database
    networks:
      mynet:
        aliases:
          - backend
    
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3001:3000
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
    networks:
      mynet:
        aliases:
          - frontend

networks:
  mynet:
    driver: bridge

volumes:
  pgdata:
