version: '3'
services:
  database:
    image: postgres:13.0-alpine
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=uic
      - POSTGRES_PASSWORD=abcd1234
      - POSTGRES_DB=mydb
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      mynet:
        aliases:
          - database
    hostname: database
    command: postgres -c 'max_connections=200'

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 5001:8000
    depends_on:
      - database
    networks:
      - mynet
    stdin_open: true
    tty: true
    command: bash -c "python manage.py makemigrations && python manage.py migrate && echo \"from django.contrib.auth import get_user_model; User = get_user_model(); User.objects.filter(username='admin').exists() or User.objects.create_superuser('admin', 'admin@uic.com', 'abcd1234')\" | python manage.py shell && python manage.py runserver 0.0.0.0:8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3001:3000
    volumes:
      - ./frontend:/app/frontend
    depends_on:
      - backend
    networks:
      mynet:
        aliases:
          - frontend

networks:
  mynet:
    driver: bridge

volumes:
  pgdata:
